spin_version = "1"
authors = ["David Gamero <david340804@gmail.com>"]
description = ""
name = "rust-is-bad"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "rust-is-bad"
source = "target/wasm32-wasi/release/rust_is_bad.wasm"
allowed_http_hosts = []
[component.trigger]
route = "/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
# watch = ["src/**/*.rs", "Cargo.toml"]
