apiVersion: apps/v1
kind: Deployment
metadata:
  name: wasmamba
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wasmamba
  template:
    metadata:
      labels:
        app: wasmamba
    spec:
      containers:
        - name: wasmamba
          image: ghcr.io/davidgamero/wasmambo5
          command: ["/"]
---
apiVersion: v1
kind: Service
metadata:
  name: wasmamba
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: wasmamba
